### ISSUE TITLE
An introduction

### ISSUE THREAD

**Issue by wezm** [i18n-concept/rust-discuss#11]
Hi :wave:,

Manish suggested I introduce myself to this effort via an issue, so here goes: I work at YesLogic on [Prince](https://www.princexml.com/). I've recently been replacing our C based Unicode/UCD 9.0 related code with Rust and updating it to Unicode 12.1.

We use lookup tables that trade off some space for faster lookups than the typical binary search approach used in the Rust standard library and Unicode crates in the ecosystem. My approach has been to use [ucd-generate](https://github.com/BurntSushi/ucd-generate) to generate simple space efficient tables and then use a build script generate the lookup tables from those.

Where possible I've extended existing crates, but I've also published several new crates. I'm waiting for some initial feedback on [my first `ucd-generate` pull request](https://github.com/BurntSushi/ucd-generate/pull/15) before opening more, although BurntSushi seems busy at the moment. The thought is that when all the `ucd-generate` changes are merged I'll open PRs against the other crates that need that newer `ucd-generate` version.

So far I have:

- Added support for bidi-mirrored, joining-type, arabic-shaping, and case mapping to `ucd-generate`
- Updated [unicode-script](https://github.com/servo/unicode-script) to Unicode 12.1 data with ucd-generate and implemented the lookup table approach
- Updated [unicode-bidi](https://github.com/servo/unicode-bidi) to Unicode 12.1 data with ucd-generate and implemented the lookup table approach
- Published https://crates.io/crates/unicode-case-mapping
- Published https://crates.io/crates/unicode-general-category
- Published https://crates.io/crates/unicode-joining-type

Manish suggested this work and new crates might be relevant and from our point of view an, "ICU in Rust", is also of interest.

Regards,
Wes

**Comment by filmil** [comment]
Hello, @wezm !  I am a very big Prince fan, both the Artist and the Software.  Thanks for presenting your work, I think it's going to be super-useful.

Can you tell me more about your interest in "ICU in rust"? I've been working on this in the context of Fuchsia and exported the code we have so far at https://github.com/google/rust_icu, in case that matters.

Best regards,
F

**Comment by wezm** [comment]
Hi @filmil 

> Can you tell me more about your interest in "ICU in rust"? I've been working on this in the context of Fuchsia and exported the code we have so far at https://github.com/google/rust_icu, in case that matters.

Manish mentioned:

> A bunch of us are planning on an overarching "ICU but in rust" project that's modular and allows for different data sources.

So I was mostly expressing interest in such a thing were it to come about.

**Comment by zbraniecki** [comment]
There's definitely an interest in that. I'm building a case for making such a switch since my initial performance and memory benchmarks indicate very real wins.

**Comment by BurntSushi** [comment]
Sorry about the tardiness in responding to `ucd-generate`. I've been somewhat away from the computer as of late, and while I was keeping in eye on email, I was only responding to easy/urgent things.

Happy to discuss the role of `ucd-generate` moving forward. For the most part, there are two key evolutions I want it go through soonish:

* [Fix a cyclic build dependency between `ucd-generate`, `regex-syntax` and `regex-automata`.](https://github.com/BurntSushi/ucd-generate/issues/11)
* Probably migrate the output generation logic to use a proper templating library, perhaps [`tinytemplate`](https://crates.io/crates/tinytemplate), since the current output code has gotten a bit hairy.

But beyond that, I'm mostly happy to have `ucd-generate` become a kitchen sink that can be build out over time. When I first created it, I had intended it to be a temporary measure until the UNIC project was ready to fill that niche, but I don't know what the status of UNIC is.

**Comment by sffc** [comment]
Hi @wezm!

This project is now chartered as ICU4X in Unicode.  We have a lot of headroom, especially in areas involving Unicode properties.  Take a look at some of the open issues and subscribe for updates!

https://github.com/unicode-org/icu4x
